name: Mieru Plugin Release Build
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Release (y/n)'
        required: false
      tag:
        description: 'Release Tag'
        required: false
jobs:
  native:
    name: Native Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Status
        run: git submodule status 'plugin/mieru/*' > mieru_status
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache-dependency-path: "**/go.sum"
      - name: Mieru Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            plugin/mieru/src/main/jniLibs
          key: ${{ hashFiles('.github/workflows/*', 'bin/lib/mieru/*', 'mieru_status') }}
      - name: Native Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export ANDROID_NDK_HOME=${ANDROID_NDK_LATEST_HOME}
          ./run plugin mieru
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    needs:
      - native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Status
        run: git submodule status 'plugin/mieru/*' > mieru_status
      - name: Setup Java
        uses: actions/setup-java@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Mieru Cache
        uses: actions/cache@v4
        with:
          path: |
            plugin/mieru/src/main/jniLibs
          key: ${{ hashFiles('.github/workflows/*', 'bin/lib/mieru/*', 'mieru_status') }}
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle.kts') }}
      - name: Release Build
        env:
          SKIP_BUILD: on
          BUILD_PLUGIN: mieru
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./gradlew :plugin:mieru:assembleOssRelease
          APK=$(find plugin/mieru/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname "$APK")
          echo "APK=$APK" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: ${{ env.APK }}
  publish:
    name: Publish Release
    if: github.event.inputs.publish == 'y' && github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Donwload Artifacts
        uses: actions/download-artifact@v4
        with:
          name: APKs
          path: artifacts
      - name: Release
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.16.2/ghr_v0.16.2_linux_amd64.tar.gz
          tar -xvf ghr.tar.gz
          mv ghr*linux_amd64/ghr .
          mkdir apks
          find artifacts -name "*.apk" -exec cp {} apks \;
          ./ghr -replace -prerelease -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" apks
